######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 18 18:06:43 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
